### ISSUE TITLE
No Volume for Postgress

### ISSUE THREAD

**Issue by kvebers** [zstenger93/Transcendence#290] opened 2024-03-01 08:25 UTC
When DB is restarted the client still have its session but the Postgres loses its volume. Creating User Not Defined Error in JavaScript.

**Comment by zstenger93** [comment] 2024-03-12 10:29
It was like that for a reason while working on the login stuff, not a bug so I will close this. Will merge the PR later when we are almost done.

**Closed by zstenger93** 2024-03-12 10:29 UTC
